name: EKS DR Failover

on:
  workflow_dispatch:

jobs:
  failover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Velero CLI
        run: |
          curl -L https://github.com/vmware-tanzu/velero/releases/download/v1.12.3/velero-v1.12.3-linux-amd64.tar.gz | tar xz
          sudo mv velero-v1.12.3-linux-amd64/velero /usr/local/bin

      - name: Trigger restore
        run: |
          velero restore create --from-backup daily-backup --wait

      - name: Validate restoration
        run: |
          kubectl get all -n my-app
